"use client";
import { useMemo, useState } from "react";
import { SearchIcon } from "@/components/ui/icons";
import { ProductCard } from "./product-card";
import { products } from "./products-data";

const categories=["All","Sofas","Chairs","Tables","Beds","Storage","Lighting","Outdoor"];
const colors=["White","Black","Beige","Brown","Green"];
const materials=["Wood","Metal","Fabric","Stone","Rattan"];

export function ProductCatalog(){
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("All"); const [maxPrice,setMaxPrice]=useState(2000); const [color,setColor]=useState(""); const [material,setMaterial]=useState(""); const [sort,setSort]=useState("featured"); const [filtersOpen,setFiltersOpen]=useState(false);
 const filtered=useMemo(()=>{const list=products.filter(p=>(category==="All"||p.category===category)&&p.price<=maxPrice&&(!color||p.color===color)&&(!material||p.material===material)&&p.name.toLowerCase().includes(query.toLowerCase()));if(sort==="low")return [...list].sort((a,b)=>a.price-b.price);if(sort==="high")return [...list].sort((a,b)=>b.price-a.price);return list},[query,category,maxPrice,color,material,sort]);
 const reset=()=>{setQuery("");setCategory("All");setMaxPrice(2000);setColor("");setMaterial("");setSort("featured")};
 return <section className="section-pad"><div className="page-shell"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><label className="relative flex-1"><SearchIcon className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-black/40"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search furniture, e.g. sofa, chair, table..." className="w-full rounded-xl border border-black/10 bg-white py-4 pl-12 pr-4 text-sm outline-none ring-[#6c46ff] focus:ring-2"/></label><div className="flex gap-3"><button onClick={()=>setFiltersOpen(!filtersOpen)} className="rounded-xl border border-black/10 bg-white px-5 py-3 text-sm font-bold lg:hidden">Filters</button><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort products" className="rounded-xl border border-black/10 bg-white px-4 py-3 text-sm outline-none"><option value="featured">Featured</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option></select></div></div>
 <div className="mt-5 flex gap-2 overflow-x-auto pb-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold ${category===c?"bg-[#6c46ff] text-white":"border border-black/10 bg-white"}`}>{c}</button>)}</div>
 <div className="mt-8 grid gap-8 lg:grid-cols-[230px_1fr]"><aside className={`${filtersOpen?"block":"hidden"} h-fit rounded-2xl border border-black/10 bg-white p-5 lg:block`}><div className="flex items-center justify-between border-b border-black/10 pb-4"><h2 className="text-lg font-bold">Filters</h2><button onClick={reset} className="text-xs font-bold text-[#6c46ff]">Reset All</button></div><FilterGroup title="Price"><input type="range" min="250" max="2000" step="50" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))} className="w-full accent-[#6c46ff]"/><div className="mt-2 flex justify-between text-xs text-black/45"><span>$250</span><span>Up to ${maxPrice.toLocaleString()}</span></div></FilterGroup><FilterGroup title="Color">{colors.map(c=><label key={c} className="flex cursor-pointer items-center gap-3 py-1.5 text-sm"><input type="radio" name="color" checked={color===c} onChange={()=>setColor(c)} className="accent-[#6c46ff]"/><span className="h-3.5 w-3.5 rounded-full border border-black/10" style={{background:c.toLowerCase()}}/>{c}</label>)}</FilterGroup><FilterGroup title="Material">{materials.map(m=><label key={m} className="flex cursor-pointer items-center gap-3 py-1.5 text-sm"><input type="radio" name="material" checked={material===m} onChange={()=>setMaterial(m)} className="accent-[#6c46ff]"/>{m}</label>)}</FilterGroup></aside>
 <div><div className="mb-5 flex items-center justify-between"><p className="text-sm text-black/50"><strong className="text-black">{filtered.length}</strong> products found</p><p className="hidden text-xs text-black/40 sm:block">Every product is AR ready</p></div>{filtered.length?<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(product=><ProductCard key={product.name} product={product}/>)}</div>:<div className="grid min-h-80 place-items-center rounded-2xl bg-white text-center"><div><p className="text-xl font-bold">No products found</p><button onClick={reset} className="mt-3 text-sm font-bold text-[#6c46ff]">Clear filters</button></div></div>}<div className="mt-10 flex justify-center gap-2"><button className="grid h-10 w-10 place-items-center rounded-lg border border-black/10 bg-white">‹</button><button className="grid h-10 w-10 place-items-center rounded-lg bg-[#6c46ff] text-sm font-bold text-white">1</button><button className="grid h-10 w-10 place-items-center rounded-lg border border-black/10 bg-white text-sm">2</button><button className="grid h-10 w-10 place-items-center rounded-lg border border-black/10 bg-white text-sm">3</button><button className="grid h-10 w-10 place-items-center rounded-lg border border-black/10 bg-white">›</button></div></div></div></div></section>
}

function FilterGroup({title,children}:{title:string;children:React.ReactNode}){return <div className="border-b border-black/10 py-5 last:border-0"><h3 className="mb-3 text-sm font-bold">{title}</h3>{children}</div>}
